- name: Ensure required packages are installed (Debian)
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
  when: ansible_os_family == 'Debian'

- name: Ensure required packages are installed (RedHat)
  yum:
    name:
      - wget
    state: present
  when: ansible_os_family == 'RedHat'

- name: Download Jenkins GPG key
  ansible.builtin.get_url:
    url: "{{ jenkins_gpg_key }}"
    dest: "{{ jenkins_gpg_dest }}"
  when: ansible_os_family == 'Debian'

- name: Add Jenkins repository (Debian)
  template:
    src: jenkins.repo.j2
    dest: /etc/apt/sources.list.d/jenkins.list
  when: ansible_os_family == 'Debian'

- name: Download Jenkins repository file (RedHat)
  ansible.builtin.get_url:
    url: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"
    dest: "/etc/yum.repos.d/jenkins.repo"
  when: ansible_os_family == 'RedHat'

- name: Import Jenkins GPG key (RedHat)
  rpm_key:
    state: present
    key: "https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key"
  when: ansible_os_family == 'RedHat'

- name: Update apt package cache
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install required packages (Debian)
  apt:
    name: 
      - openjdk-17-jre
      - fontconfig
    state: present
  when: ansible_os_family == 'Debian'

- name: Install required packages (RedHat)
  yum:
    name:
      - java-11-openjdk
      - fontconfig
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install Jenkins (Debian)
  apt:
    name: jenkins
    state: present
  when: ansible_os_family == 'Debian'
  notify: start jenkins

- name: Install Jenkins (RedHat)
  yum:
    name: jenkins
    state: present
  when: ansible_os_family == 'RedHat'
  notify: start jenkins

- name: Start Jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes
  notify: start jenkins

